version: "3"

volumes:
  nextcloud-app:
  ghost-app:

services:

  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-app:/var/www/html
    ports:
      - 8080:80

  ghost-app:
    image: ghost:4-alpine
    restart: always
    ports:
      - 3001:2368
    volumes:
      - ghost-app:/var/lib/ghost/content
    environment:
      - url=http://localhost:3001
      - NODE_ENV=development