version: "3"


volumes:
  nextcloud-app:
  ghost-app:
  jellyfin-app:
  matrix-conduit-app:


services:

  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-app:/var/www/html
    ports:
      - 8080:80

  ghost-app:
    image: ghost:4-alpine
    restart: always
    ports:
      - 3001:2368
    volumes:
      - ghost-app:/var/lib/ghost/content
    environment:
      - url=http://localhost:3001
      - NODE_ENV=development

  jellyfin-app:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: always
    volumes:
      - jellyfin-app:/config
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London

  element-app:
      image: vectorim/element-web:latest
      restart: always
      ports:
          - 8009:80
      volumes:
          - $PWD/element-app/element_config.json:/app/config.json

